language: ruby
rvm:
 - 2.3.5

env:
  global:
    - CC_TEST_REPORTER_ID=5821733a348c2023a8c0aa2a79e6516f92d1d32d26c240329c5b88dc89f5601b
services:
  - postgresql

env:
  - DB=postgresql
before_script:
  - psql -c 'create database travis' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

