services:
  - postgresql

env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
before_script:
  - psql -c 'create database travis' -U postgres

language: ruby
rvm:
 - 2.3.5
