default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 30
  host: ec2-79-125-117-53.eu-west-1.compute.amazonaws.com
  username: ddefvadesyfatd
  password: a00b06057420b76cb8d8ba9b0da0a5e0ef56f7996c54859f76333e56549c748d
  port: 5432
  database: dappu14s8q21ei

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default