default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: projet_dev
  
test:
  <<: *default
  database: projet_test

production:
  <<: *default
  database: projet
