
default: &default
  adapter: postgresql
  encoding: unicode
  encoding: utf8
  pool: 15
  host: localhost
  username: agent
  password: agent

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
