
default: &default
  adapter: postgresql
  encoding: unicode
  encoding: utf8
  pool: 15
  host: 127.0.0.1
  username: agent
  password: agent
  
development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
